Item03/depois/CasaDoCodigo.MVC/Areas/Catalogo/Models/ViewModels/CarrosselViewModel.cs
using CasaDoCodigo.Areas.Catalogo.Models;
using System.Collections.Generic;

namespace CasaDoCodigo.Areas.Catalogo.Models.ViewModels
{
    public class CarrosselViewModel
    {
        public CarrosselViewModel()
        {

        }

        public CarrosselViewModel(Categoria categoria, List<Produto> produtos, int numPaginas, int tamanhoPagina)
        {
            Categoria = categoria;
            Produtos = produtos;
            NumPaginas = numPaginas;
            TamanhoPagina = tamanhoPagina;
        }

        public Categoria Categoria { get; set; }
        public List<Produto> Produtos { get; set; }
        public int NumPaginas { get; set; }
        public int TamanhoPagina { get; set; }
    }
}

Item03/depois/CasaDoCodigo.MVC/Areas/Catalogo/ViewComponents/CarrosselPaginaViewComponent.cs
using CasaDoCodigo.Areas.Catalogo.Models.ViewModels;
using CasaDoCodigo.Areas.Catalogo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace CasaDoCodigo.Areas.Catalogo.ViewComponents
{
    public class CarrosselPaginaViewComponent : ViewComponent
    {
        public CarrosselPaginaViewComponent()
        {

        }

        public IViewComponentResult Invoke(List<Produto> produtosNaCategoria, int indicePagina, int tamanhoPagina)
        {
            var produtosNaPagina =
                produtosNaCategoria
                .Skip(indicePagina * tamanhoPagina)
                .Take(tamanhoPagina)
                .ToList();

            return View("Default",
                new CarrosselPaginaViewModel(produtosNaPagina, indicePagina));
        }
    }
}

Item03/depois/CasaDoCodigo.MVC/Areas/Catalogo/ViewComponents/CarrosselViewComponent.cs
using CasaDoCodigo.Areas.Catalogo.Models.ViewModels;
using CasaDoCodigo.Areas.Catalogo.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace CasaDoCodigo.Areas.Catalogo.ViewComponents
{
    public class CarrosselViewComponent : ViewComponent
    {
        public CarrosselViewComponent()
        {

        }

        public IViewComponentResult Invoke(Categoria categoria, List<Produto> produtos, int tamanhoPagina)
        {
            var produtosNaCategoria = produtos
                .Where(p => p.Categoria.Id == categoria.Id)
                .ToList();
            int pageCount = (int)Math.Ceiling((double)produtosNaCategoria.Count() / tamanhoPagina);

            return View("Default",
                new CarrosselViewModel(categoria, produtosNaCategoria, pageCount, tamanhoPagina));
        }
    }
}

Item03/depois/CasaDoCodigo.MVC/Areas/Catalogo/Views/Home/Components/Carrossel/Default.cshtml
@using CasaDoCodigo.Areas.Catalogo.Models.ViewModels;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, CasaDoCodigo.MVC
@model CarrosselViewModel

<h3>@Model.Categoria.Nome</h3>

<div id="my-carousel-@Model.Categoria.Id" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
        @{
            for (int pageIndex = 0; pageIndex < Model.NumPaginas; pageIndex++)
            {
                <vc:carrossel-pagina indice-pagina="@pageIndex"
                                     produtos-na-categoria="@Model.Produtos"
                                     tamanho-pagina="@Model.TamanhoPagina"></vc:carrossel-pagina>
            }
        }
    </div>
    <partial name="_NavegacaoCarrossel" model="@Model.Categoria" />
</div>