Item03/depois/CasaDoCodigo.MVC/Areas/Catalogo/Models/ViewModels/CarrosselPaginaViewModel.cs
using CasaDoCodigo.Areas.Catalogo.Models;
using System.Collections.Generic;

namespace CasaDoCodigo.Areas.Catalogo.Models.ViewModels
{
    public class CarrosselPaginaViewModel
    {
        public CarrosselPaginaViewModel()
        {

        }

        public CarrosselPaginaViewModel(List<Produto> produtos, int indicePagina)
        {
            Produtos = produtos;
            IndicePagina = indicePagina;
        }

        public List<Produto> Produtos { get; set; }
        public int IndicePagina { get; set; }
    }
}

Item03/depois/CasaDoCodigo.MVC/Areas/Catalogo/ViewComponents/ProdutoCardViewComponent.cs
using CasaDoCodigo.Areas.Catalogo.Models;
using Microsoft.AspNetCore.Mvc;

namespace CasaDoCodigo.Areas.Catalogo.ViewComponents
{
    public class ProdutoCardViewComponent : ViewComponent
    {
        public ProdutoCardViewComponent()
        {

        }

        public IViewComponentResult Invoke(Produto produto)
        {
            return View("Default", produto);
        }
    }
}

Item03/depois/CasaDoCodigo.MVC/Areas/Catalogo/Views/Home/Components/CarrosselPagina/Default.cshtml
@using CasaDoCodigo.Areas.Catalogo.Models.ViewModels
@addTagHelper *, CasaDoCodigo.MVC
@model CarrosselPaginaViewModel

<div class="item @(Model.IndicePagina == 0 ? "active" : "")">
    <div class="row">
        @{
            foreach (var produto in Model.Produtos)
            {
                <vc:produto-card produto="@produto"></vc:produto-card>
            }
        }
    </div>
</div>